### ISSUE TITLE
无法更改图标和背景

### ISSUE THREAD

**Issue by poppin7c** [canisminor1990/sd-web-ui-kitchen-theme#10]
更改图标会报以下错误
![1678160089049](https://user-images.githubusercontent.com/46238464/223314123-ca388c0e-71e1-4ee8-b5cb-639d7a6599e3.jpg)

**Comment by Dreamkaka** [comment]
和你一样，不知道是不是要改webui启动那不能直接从那个选项卡改（作者说还是个半成品）
