### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Nacurutu** [canisminor1990/sd-web-ui-kitchen-theme#14]
Hi, as you are using code from: https://github.com/Gerschel/sd-web-ui-quickcss/

I recommend you, at least, mention @Gerschel in your repo.

Also, you are using code from my CSS files:

https://github.com/Nacurutu/Dark-Themes-SD-WebUI-Automatic1111

**Comment by Gerschel** [comment]
Makes sense. I see the copied work as well.

**Comment by Nacurutu** [comment]
???

**Comment by canisminor1990** [comment]
Sorry for the delay. I closed the issues before 1.0.0 in bulk without reviewing the previous information. I didn't anticipate entering the plugin market of sd webui before 1.0.0, so I used some existing theme projects to quickly create the theme I wanted. After 1.0.0, I have completely deleted that part of the code. However, if you are willing, I can add your link.

**Comment by Nacurutu** [comment]
no worries.. is just a matter of ethics in github communities... u can use any code u want, just mention the owner in ur readme file and it is all ok... i don't mind if anyone use the css files I did... but @Gersche l's work should be recognized... 

every coder is always welcome...

keep working on your extension 👍🏻
