### ISSUE TITLE
it is not working because of your new update 

### ISSUE THREAD

**Issue by hannanrozal** [canisminor1990/sd-web-ui-kitchen-theme#17]
Please Fix This broo!! 

![image](https://user-images.githubusercontent.com/75463261/228385954-21b36e28-fc9e-43de-b85d-49042ee3b210.png)

**Comment by NinjaDanny87** [comment]
Having the same issue, here's my post.

https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/15

**Comment by canisminor1990** [comment]
check your gradio version, only support >= 3.23.0, minimum requirements sd-webui [4c1ad74](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4c1ad743e3baf1246db0711aa0107debf036a12b)

**Comment by NinjaDanny87** [comment]
Just updated SDWebui gradio gradio: 3.16.2 > gradio: 3.23.0. 

I can confirm it has fixed the issue. Thanks for the help @canisminor1990 

For anyone seeing this do a FORCE UPDATE Webui and it should update to gradio: 3.23.0

**Comment by hannanrozal** [comment]
Thanks Bro Its working now @canisminor1990
