### ISSUE TITLE
Tabs buttons block dropdown option

### ISSUE THREAD

**Issue by Chrisr0** [canisminor1990/sd-web-ui-kitchen-theme#18]
With Kitchen installed, dropdown options are blocked by tabs underneath. Happens on all quicksettings dropdowns.

On the included screenshot you can see me hovering over "None" option but "HakuImg" is activated instead.
![obraz](https://user-images.githubusercontent.com/36136394/228706440-d5a5e03f-898f-48ed-92c8-65b89f85de6a.png)

**Comment by canisminor1990** [comment]
fixed
