### ISSUE TITLE
Needs optimization for mobile devices

### ISSUE THREAD

**Issue by Murcielagoz99** [canisminor1990/sd-web-ui-kitchen-theme#19]
I love this theme, I appreciate the work you've put into it. With that being said, I am slightly disappointed that I have to stick to the Cappuchin theme instead of using yours! I prefer to use my mobile device and the tabs run off the screen! That's the only real downside I've noticed so far, but I'm unable to access certain tabs so I need to rely on an extension that merges the remaining tabs over. Thank you for the awesome theme! By the way - I would love to update the logo image to one that I've generated!

**Comment by MrKuenning** [comment]
Similar request: https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/4

**Comment by younyokel** [comment]
Didn't know WebUI works on mobile

**Comment by MrKuenning** [comment]
I published mine with a dynamic DNS and reverse proxy and use my phone all the time to generate stuff.

![2023-04-07 22_46_01-Window](https://user-images.githubusercontent.com/16549268/230737718-d350f03a-f017-4d26-aa0e-eec9e27cc56d.jpg)

**Comment by canisminor1990** [comment]
Fixed
