### ISSUE TITLE
thumb mode for "show extra network" CSS doesn't work

### ISSUE THREAD

**Issue by Aurety** [canisminor1990/sd-web-ui-kitchen-theme#2]
Thanks for this layout, awesome and hard ! A small problem with the style of thumb mode for "show extra network" CSS, the previews are large and the title is offseted. Thanks again !

![image](https://user-images.githubusercontent.com/113844207/222151531-14bb5503-38d7-4c12-93b5-f6830049cd5e.png)

**Comment by Aurety** [comment]
I tried with the theme->cardssize parameter but maybe i'm wrong, but i can't change anything.

**Comment by MrKuenning** [comment]
Yeah, I love a lot about the theme, but not being able to make my 240 Loras small is a deal breaker for me.

**Comment by cibernicola** [comment]
create a file called "user.css" un WebUI root folder or add this if file exists:
```
.extra-network-thumbs .card {
    height: 150px!important;
    width: 100px!important;
}
```
Put your desired values. It works.

**Comment by Aurety** [comment]
Thanks, Cibernicola ! any tips to center the title ?
