### ISSUE TITLE
Bug on CiviAI extension 

### ISSUE THREAD

**Issue by bropines** [canisminor1990/sd-web-ui-kitchen-theme#20]
Because of the bug is overlapping the header on top of the header with the buttons, because of which it becomes impossible to switch between tabs

https://github.com/civitai/sd_civitai_extension

![image](https://user-images.githubusercontent.com/57861007/229854226-9087b1f9-904b-4854-b4aa-bbbd018d34a5.png)
![image](https://user-images.githubusercontent.com/57861007/229854250-f63178cd-d574-4069-b287-65a6c38012c0.png)

**Comment by hannanrozal** [comment]
Yes Same Here

**Comment by Tobe2d** [comment]
+1

**Comment by canisminor1990** [comment]
Please check the latest version of the CiviAI plugin. I haven't encountered the above issue. How can it be reproduced?

**Comment by bropines** [comment]
> Please check the latest version of the CiviAI plugin. I haven't encountered the above issue. How can it be reproduced?


https://user-images.githubusercontent.com/57861007/230928143-6af40800-0cfe-4fdb-be0c-ae7197aad8c7.mp4
![msedge_zxW4Q9Fv66](https://user-images.githubusercontent.com/57861007/230928153-894540a5-d09e-4213-9a60-e4717779046c.png)

**Comment by bropines** [comment]
It's partially fixed. But that's not quite the right view either.

**Comment by bropines** [comment]
> It's partially fixed. But that's not quite the right view either.

My translator lets me down. Yes These bugs I noticed and they were talking about)

**Comment by Tobe2d** [comment]
Another thing as you see below the extentions tab does not shrink if the screen is smaller. it should either divide them into 2 rows or a dropdown menue will be super nice ;-)

![image](https://user-images.githubusercontent.com/4099839/230965759-8c79ff59-01a5-4048-bbe9-7bc4b7517a3e.png)

**Comment by HyperLemons** [comment]
Still there...

![image](https://user-images.githubusercontent.com/36387099/232255815-17f12d3a-7f10-4d56-ab5c-1e88f2d84c84.png)

**Comment by canisminor1990** [comment]
try the new commit

**Comment by bropines** [comment]
> try the new commit

Yep. Everything works.
![image](https://user-images.githubusercontent.com/57861007/233353281-84342ea2-fdd5-481d-8314-ebf29316e26c.png)
