### ISSUE TITLE
Quicksetting dropdowns changes to right aligned/快捷设置菜单变为右对齐

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-web-ui-kitchen-theme#28]
The quicksetting dropdowns menu has been changed to right aligned in the latest version that supports gradio 3.23, which greatly affects the user experience. As the space on the right side is occupied by hashes, the suffix name of the file also seriously affects the alignment effect. The subdirectory information on the left side makes the interface more chaotic.
快捷设置下拉菜单在最新支持gradio3.23的版本中变为了右对齐，这极大影响了使用体验。因为右侧的空间会被哈希值占据，文件的后缀名也严重影响了对齐效果，处于左侧的子目录信息更是让界面变得更加混乱。
![I QO (R{9MT8{{B_`XZ0AH5](https://user-images.githubusercontent.com/115604775/231515474-7ab34860-50bf-48b4-94dc-074f92303764.png)

**Comment by antorio** [comment]
agree. right aligned on clustered small texts is so annoying. Confusing the mind, hurting eyes. Does anybody has a workaround on this?

**Comment by bbecausereasonss** [comment]
Totally, super difficult to browse quickly.

**Comment by anne43983959** [comment]
> fixed

Good job!
