### ISSUE TITLE
Love what you’re going for! But mobile…

### ISSUE THREAD

**Issue by Murcielagoz99** [canisminor1990/sd-web-ui-kitchen-theme#30]
Great implementations! Although this is what it’s looking like on mobile at the moment, almost unable to use the UI at all anymore!
EDIT: I found the sidebar slider and once it's closed I'm able to use the UI like normal.
![FBE2E10F-2499-43BE-829A-731EA5D1BDCB](https://user-images.githubusercontent.com/128203225/233389137-7738a18b-ac67-4bde-a30b-0c42ac93511d.jpeg)

**Comment by Murcielagoz99** [comment]
Here's what we're looking like on desktop as well. 
![image](https://user-images.githubusercontent.com/128203225/233390811-1af9b491-5c89-427d-aa86-bfe230d8c85c.png)

Again, I appreciate your hard work and check for updates/changes frequently! I'm not in the best position at the moment but I would also be happy to contribute maybe a small amount for your efforts.

**Comment by robonxt** [comment]
same issue as well. enjoying the new update, however it no longer works properly on phones. Perhaps on tablets, but overall the mobile experience doesn't work at the moment.
