### ISSUE TITLE
When you switch to other tabs, all tags are lost

### ISSUE THREAD

**Issue by bropines** [canisminor1990/sd-web-ui-kitchen-theme#32]
https://user-images.githubusercontent.com/57861007/233530407-6ef3c9d0-a17e-4836-8e61-0c26869ea457.mp4

**Comment by ColorfanXP** [comment]
Just experienced this myself, though oddly enough, after entering stuff back in, and trying another tab,, it only seems to happen when clicking certain tabs.

**Comment by canisminor1990** [comment]
fixed

**Comment by bropines** [comment]
Is it possible to fix this bunch of extra stripes? I don't understand where they come from
![image](https://user-images.githubusercontent.com/57861007/233650877-29d0254b-acd3-4433-9882-a53986296c60.png)
