### ISSUE TITLE
’Send to’ button is invalid & conflicts with Tag Autocomplete extension | send to按钮失效，并且和Tag Autocomplete插件发生冲突

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-web-ui-kitchen-theme#33]
1. In the latest version of the Kitchen theme, when using the ‘send to’ button to send the generated information of the image to the txt2img or img2img page, the effect of jumping to the page is lost, and the generated information is not filled in the corresponding position

2. Tag Autocomplete extension (https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) can freely set the color of different categories of tags in the options, but in the latest version of Kitchen theme, all Tag Autocomplete Options are all white(as shown in Figure 1 and Figure 2)

3. The built-in screenshot function of the browser is interfered. When using the function of capturing the entire webpage, only the currently displayed area can be captured(as shown in Figure 3 and Figure 4)

Suggestion: Disable the function of writing tags in the sidebar, consider moving the sidebar to the top area again, and make it collapsible, or automatically display when the mouse is close (preferably with the function of freezing the panel)

ps: Thank you for your outstanding contribution to the interface beautification, I like the changes in the last few versions very much, but I also can't ignore the impact it has on the actual function, so I put forward some ideas to help this extension Become more practical, and hope that subsequent versions can pay more attention to extension compatibility issues

1. 在最新版的Kitchen theme中，使用send to按钮将图片的生成信息发送到txt2img或者img2img页面的时候，失去了跳转页面的效果，并且生成信息也没有填入对应的位置

2. Tag Autocomplete插件可以自由设置不同类别的tag在选项中的颜色，但是在最新版的Kitchen theme中，所有Tag Autocomplete的选项都变成了白色

3. 浏览器自带的截图功能受到干扰，使用截取整个网页功能时仅能截取到当前已显示的区域

建议：停用侧边栏写入tag的功能，考虑把侧边栏重新移动到顶部区域，并改为可折叠的，或鼠标靠近时自动显示（最好配合可冻结面板的功能）

ps：真的很感谢你为界面美化所作出的杰出贡献，我非常喜欢最近几个版本的改动，但我同样无法忽略它对实际功能带来的影响，因此我提出一些看法希望能帮助这个扩展变得更实用，希望后续的版本可以更多关注扩展兼容性问题
![1](https://user-images.githubusercontent.com/115604775/233540577-8c23461f-8e70-4b41-8e5c-cc4bcce92c51.png)
————————————————————Figure 1————————————————————
·
·
![2](https://user-images.githubusercontent.com/115604775/233540584-016dd3b6-9240-4e9a-bac5-8bbae99b9ccd.png)
————————————————————Figure 2————————————————————
·
·
![3](https://user-images.githubusercontent.com/115604775/233540589-c843b90e-d72d-4a73-bba0-4dbcdfbecbdb.png)
————————————————————Figure 3————————————————————
·
·
![4](https://user-images.githubusercontent.com/115604775/233540595-6b41122a-9a87-46d6-bcec-eb31d8de4714.png)
————————————————————Figure 4————————————————————

**Comment by canisminor1990** [comment]
fixed

**Comment by canisminor1990** [comment]
修复Bug外，关于侧边栏部分有几个待论点，如果放置顶部时会导致垂直可操作区域过小，且无法承载过多的快捷工具，目前的想法是把低频操作工具尽可能塞入可折叠面板中

**Comment by yuno779** [comment]
When I switch tabs, Prompt and Negative Prompt are cleared
当我切换标签页的时候，Prompt和Negative Prompt会被清空,
![image](https://user-images.githubusercontent.com/131428984/233609471-9169e2b7-5a89-4c2a-9edc-4effe186ad24.png)

**Comment by canisminor1990** [comment]
> When I switch tabs, Prompt and Negative Prompt are cleared
> 
> 当我切换标签页的时候，Prompt和Negative Prompt会被清空,
> 
> ![image](https://user-images.githubusercontent.com/131428984/233609471-9169e2b7-5a89-4c2a-9edc-4effe186ad24.png)
> 
> 

Try the newest commit

**Comment by yuno779** [comment]
> > When I switch tabs, Prompt and Negative Prompt are cleared
> > 当我切换标签页的时候，Prompt和Negative Prompt会被清空,
> > ![image](https://user-images.githubusercontent.com/131428984/233609471-9169e2b7-5a89-4c2a-9edc-4effe186ad24.png)
> 
> Try the newest commit

![image](https://user-images.githubusercontent.com/131428984/233627862-9acd3ac0-d54a-4ca2-b16d-d95ae4264149.png)

But there was another bug with the new version: the top section was always white, forcing me to use a white screen
但是新版本出现了别的bug：顶上部分一直是白色的，导致我不得不使用白色界面

**Comment by anne43983959** [comment]
> 修复Bug外，关于侧边栏部分有几个待论点，如果放置顶部时会导致垂直可操作区域过小，且无法承载过多的快捷工具，比如以下设置就会造成灾难：
> 
> ```
> sd_model_checkpoint, sd_vae, CLIP_stop_at_last_layers, img2img_background_color, img2img_color_correction, samples_save, samples_format, grid_save, return_grid,  n_rows, live_previews_enable, show_progress_every_n_steps, live_preview_refresh_period
> ```
> 
> 目前的想法是把低频操作工具尽可能塞入可折叠面板中

个人认为，侧边面板可能是干扰页面截图的主因，虽然比起另外两个问题页面截图是次要矛盾，还是希望有朝一日可以实现鼠标悬停显示侧边栏，移开后缩回，侧边栏只短暂遮挡一部分页面内容（和旧版本半透明的顶部选项卡相似，当滚动条不处于页面顶端的时候，虽然选项卡会遮挡部分页面内容，但不影响截取整个网页的截屏操作），而不是挤占页面空间，通过在侧边栏内置入一个冻结按钮实现长时间显示侧边栏
