### ISSUE TITLE
The top bar is always white顶部栏总是白色的

### ISSUE THREAD

**Issue by yuno779** [canisminor1990/sd-web-ui-kitchen-theme#38]
新版本出现了别的bug：顶上部分一直是白色的，导致我不得不使用白色界面
The new version has another bug: the top section is always white, causing me to use a white screen
![image](https://user-images.githubusercontent.com/131428984/233628230-67bd924f-f9cf-43c7-ade8-90b1952cc1f4.png)

**Comment by canisminor1990** [comment]
能贴一下你的插件列表，我本地并没有遇到，右上角切换主题也没用么？

**Comment by yuno779** [comment]
![image](https://user-images.githubusercontent.com/131428984/233637120-a5ee797f-f25b-4c30-b7f1-80a0c0da6a1a.png)
![image](https://user-images.githubusercontent.com/131428984/233637146-20bae478-f16e-4137-a17d-74960b9145fd.png)
![image](https://user-images.githubusercontent.com/131428984/233637186-8ef29ca8-9c99-408d-be0f-de136ea4bfe4.png)
![image](https://user-images.githubusercontent.com/131428984/233637416-9cdeb818-ea88-4713-ab91-b76c168f224e.png)
切换主题也是没用的，我的系统用的是黑色主题白色界面

**Comment by yuno779** [comment]
> 能贴一下你的插件列表，我本地并没有遇到，右上角切换主题也没用么？

我把扩展依次关闭检查了一边，发现是这个扩展的问题：https://github.com/todhm/sd_feed
