### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by MrKuenning** [canisminor1990/sd-web-ui-kitchen-theme#4]
There are several issues using this theme on mobile.

The biggest being unable to scroll over and select a different tab
And being unable to select a style from the dropdown.
Many UI elements overlapping

I actually like how the top tabs area stays small and compact, but its important to be able to at least scroll sideways to select a different tab.

![Screenshot_20230302-132303.png](https://user-images.githubusercontent.com/16549268/222573472-b8343d64-e65d-42ff-b58a-899c1419f1a1.png)

**Comment by halr9000** [comment]
I also am a very frequent mobile user, would love to be able to use the theme from phone/tablet.

**Comment by MrKuenning** [comment]
I have noticed in the newest update the button overlap no longer happens.  Now we just need to solve the tab scrolling and I won't have to disable the theme at the end of every day when I switch to mobile.   :-)
