### ISSUE TITLE
Conflict with Stable-Diffusion-Webui-Civitai-Helper extension

### ISSUE THREAD

**Issue by tsound97** [canisminor1990/sd-web-ui-kitchen-theme#42]
In Stable-Diffusion-Webui-Civitai-Helper extension, click the **Refresh** button will make the additional network show 4 icon bottom(each have different function)
![image](https://user-images.githubusercontent.com/112967097/233770587-a3c5e48b-2351-47b6-87e4-b7351d50c25b.png)
![image](https://user-images.githubusercontent.com/112967097/233770593-69ad065a-4c8b-48bb-8b34-c7dcec4a1886.png)

But after the update the kitchen theme yesterday, when I click the **Refresh** button, it only works for the additional network in **T.I.** tab, not work in **Hypernetwork** tab, **ckpt** tab and **Lora** tab.
![@0AM8IU@O3CAY%%ZHXFC({T](https://user-images.githubusercontent.com/112967097/233770831-b06e58b9-4951-41ab-96a9-f53eeee6e0ec.png)
![~M`1{0394$(QKMM$U $TJHQ](https://user-images.githubusercontent.com/112967097/233770851-2722c82f-155c-4fd1-afe2-554d33375077.png)

**Comment by canisminor1990** [comment]
Try to use this Extra-Networks setting:
- thumbs
- width: 86
- height: 128

**Comment by Piscabo** [comment]
Same problem here, I will try this fix in the meantime.
