### ISSUE TITLE
windows下，顶部控件显示有问题

### ISSUE THREAD

**Issue by l5ee** [canisminor1990/sd-web-ui-kitchen-theme#46]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/18050990/233793696-20bfe90d-55ab-49cf-b4fa-ad8fef315a6e.png">

**Comment by bropines** [comment]
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/18050990/233793696-20bfe90d-55ab-49cf-b4fa-ad8fef315a6e.png">

Similar situation. + Dark theme doesn't work

**Comment by canisminor1990** [comment]
Does the latest version have this issue? I cannot reproduce it on my end.

**Comment by bropines** [comment]
> 最新的版本有这个问题么？我这边无法复现 Does the latest version have this issue? I cannot reproduce it on my end.

![image](https://user-images.githubusercontent.com/57861007/233794566-6c39cd93-2a94-4151-8a4e-a4a62d5ebad3.png)

**Comment by yueeng** [comment]
![image](https://user-images.githubusercontent.com/4374375/233794638-d1d88890-b15f-4dca-830f-4ca15238166b.png)

**Comment by canisminor1990** [comment]
try it ?

**Comment by canisminor1990** [comment]
What browser are you using? I have only tested it successfully on Chrome.
我只在 chrome 中测试通过

**Comment by yueeng** [comment]
![image](https://user-images.githubusercontent.com/4374375/233795667-c2c617d3-d6ac-4335-9503-a7b488ad407b.png)
还是不行

**Comment by bropines** [comment]
> 还是不行

I tried it in chrome. Zero result

**Comment by canisminor1990** [comment]
我找到问题了！I found it , wait a moment, i will fix it

**Comment by canisminor1990** [comment]
fixed

**Comment by bropines** [comment]
Fixed(Nothing seems to fall off)

**Comment by ioncannon1333** [comment]
emmm还是不行
firefox,edge,chrome全挂
![1](https://user-images.githubusercontent.com/12558216/233826125-2e9ac7c4-af6b-48cb-8967-566e01b1306b.png)

**Comment by canisminor1990** [comment]
看看用的是不是最新版本的插件

**Comment by ioncannon1333** [comment]
> 看看用的是不是最新版本的插件

删除重新colne安装的，也试过release下载覆盖，问题相同

**Comment by canisminor1990** [comment]
![image](https://user-images.githubusercontent.com/17870709/233830830-afc07c24-458a-4edd-8959-ceb0ca079310.png)
chorme devtool error 部分 报错列表截个完整的看看

**Comment by ioncannon1333** [comment]
![QQ图片20230423172024](https://user-images.githubusercontent.com/12558216/233831173-dfae9571-584f-4128-8c8e-b77fdf80f5f9.png)

**Comment by canisminor1990** [comment]
> ![QQ图片20230423172024](https://user-images.githubusercontent.com/12558216/233831173-dfae9571-584f-4128-8c8e-b77fdf80f5f9.png)

![image](https://user-images.githubusercontent.com/17870709/233832631-9ee02a24-e572-41ed-8e85-ee36d2d154f9.png)

这行点进去截一下

**Comment by ioncannon1333** [comment]
![QQ截图20230423175729](https://user-images.githubusercontent.com/12558216/233832936-eece2f56-26b7-44a6-9a2b-f33cabc19db3.png)

**Comment by canisminor1990** [comment]
> ![QQ截图20230423175729](https://user-images.githubusercontent.com/12558216/233832936-eece2f56-26b7-44a6-9a2b-f33cabc19db3.png)

我尝试修了下，你试下最新提交的版本

**Comment by ioncannon1333** [comment]
![QQ截图20230423182038](https://user-images.githubusercontent.com/12558216/233834136-a158f42f-8c5a-4b9b-9e9d-05152392413b.png)
已修复
