### ISSUE TITLE
Deforum Model acces is missing

### ISSUE THREAD

**Issue by Piscabo** [canisminor1990/sd-web-ui-kitchen-theme#49]
Deforum is missing the interface to change model file?
![image](https://user-images.githubusercontent.com/123719842/233826723-5b7acd81-af6d-4581-b508-c47dcf44feae.png)

Should have this:
![image](https://user-images.githubusercontent.com/123719842/233826814-ec9554c4-c1a4-43c9-a5e2-d2d2e5bfe10a.png)

**Comment by canisminor1990** [comment]
the sidebar will auto collapse，now u can expand it again
