### ISSUE TITLE
ExtraNetwork default card size调整了无效果

### ISSUE THREAD

**Issue by chisdy** [canisminor1990/sd-web-ui-kitchen-theme#50]
ExtraNetwork default card size改变数值大小保存后，文字大小有应用，但是图片大小还是原来的，无法应用

**Comment by Baspla** [comment]
Sorry to comment on this closed issue, but this still doesn't seem to be resolved. Moving the slider or changing default value does not resize the cards in any way. I tested it using Version 8880ea12 (Tue Apr 25 08:08:06 2023) on Chrome and Firefox.
