### ISSUE TITLE
Prompt Boxes Fixed Height

### ISSUE THREAD

**Issue by MrKuenning** [canisminor1990/sd-web-ui-kitchen-theme#6]
In the standard UI theme, the boxes for prompt and negative prompt will scale taller and taller based on the number of lines of prompt there are.

In the Kitchen Theme, it is a fixed height and requires scrolling up and down within the box to see it all.

![2023-03-03 15_29_03-Stable Diffusion](https://user-images.githubusercontent.com/16549268/222860475-fbaeeb23-7d8d-4146-83cc-6b748b19c7b1.jpg)

**Comment by christopher-altman** [comment]
I also can't see the top of the top prompt box unless I zoom out to the minimum setting ... regardless of browser

![Screenshot 2023-03-04 at 18 29 33](https://user-images.githubusercontent.com/51588965/222894704-ae39ff96-52a4-4bc6-9228-04d68eb83b05.jpg)
![Screenshot 2023-03-04 at 18 29 22](https://user-images.githubusercontent.com/51588965/222894758-e167e92c-1614-4986-99c0-6e387b7c9dd2.jpg)

**Comment by superchefman** [comment]
I also can't see the top of the top prompt box unless I zoom out to minimum settings, regardless of browser choice, which makes it nearly impossible to use ...

![Screenshot 2023-03-04 at 18 29 33](https://user-images.githubusercontent.com/126853675/222895368-848e0111-e83b-4e9e-be12-dad8962ff711.jpg)
![Screenshot 2023-03-04 at 18 29 22](https://user-images.githubusercontent.com/126853675/222895395-776326a0-ce0b-4725-aea9-bd571b322920.jpg)

**Comment by R-ES-H** [comment]
For 2 lines you can modify your style.css in the extension folder with

#quicksettings:after {
 height: 150px;
 }
 and 
 #tabs > div:first-child {
 flex-wrap: wrap;
 }
 
 Save it in \sd-web-ui-kitchen-theme\style_choice, apply changes, pick your new style then apply changes again
