### ISSUE TITLE
Possibility of removing or resizing the logo. 

### ISSUE THREAD

**Issue by RykeWollf** [canisminor1990/sd-web-ui-kitchen-theme#8]
Hi there, loving this theme and it's right up my alley, the only problem is that I have a few quicksettings pinned to the top, so what happens is that one of the options in this case the change lora gets cut by the resolution of the monitor (1080p) and the theme doesn't adjust and keep things within the page limits. 

Not sure if by the screenshot it's clear. Is there any way to fix this? I noticed it happens mostly because of the logo placement, but it also seems that the default UI adjusts things to the page rather than keep it in the same line. 

![image](https://user-images.githubusercontent.com/87128789/222982620-227487a5-2a09-4fa9-bcb5-eebde3e9ee17.png)

**Comment by howar31** [comment]
edit style.css and change this:

#quicksettings:before {
    display: none;
}
