### ISSUE TITLE
Extensions / Settings are not visible / not wrapped.

### ISSUE THREAD

**Issue by dsully** [canisminor1990/sd-web-ui-kitchen-theme#9]
Without Kitchen:

<img width="1643" alt="CleanShot 2023-03-05 at 16 39 44@2x" src="https://user-images.githubusercontent.com/22371/222995821-6c9287c4-10ea-4203-96c0-f17f34c3e553.png">

With:

<img width="1714" alt="CleanShot 2023-03-05 at 16 39 05@2x" src="https://user-images.githubusercontent.com/22371/222995840-58dfbb37-851e-4de2-80f6-ddbf744f9a54.png">

**Comment by MrKuenning** [comment]
This was also mentioned here:
https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/4

I think a simple solution would be to allow that bar to scroll left and right, with a mouse wheel or touch.

I like how it tightens and cleans up the top of the screen.

**Comment by dsully** [comment]
Yes, a scrolling bar would be great as opposed to a wrap. I also like how it tightens up the top of the view.

**Comment by ghostsquad** [comment]
Yes, this is a problem. I will have to uninstall this theme (though I love it) because I can't access all the tabs.

**Comment by drtentaculous** [comment]
ello, to fix that, change the block ".dark .border-b-2.flex-wrap.dark\:border-gray-700" line 354, it's not very pretty for now but it works.

-webkit-scrollbar{width:2px;height:2px;}
-webkit-scrollbar-button{width:2px;height:2px;}

.dark .border-b-2.flex-wrap.dark\:border-gray-700 {
  border: none !important;
  margin-bottom: var(--margin);
  overflow-x: scroll; /* or overflow-x: scroll; */
}

**Comment by dsully** [comment]
That works, but definitely not pretty. :)

**Comment by halr9000** [comment]
Would also love to see a fix for this. Had to reduce down to 75% (making the text too small to read easily) in order to access extensions/settings tabs.

**Comment by neoOpus** [comment]
Here is a quick fix (a userstyle) that you can add to Stylus or Stylish (or any other userstyle manager extension), to scroll just use the mouse horizontal scrolling feature if you have that (Logitech) but it is not the recommended way since it tend to be very slow... I suggest to use <kbd>Shift</kbd> + Mouse Scroll Wheel, I will check back here to answer questions :)

```
@-moz-document url-prefix("http://localhost:7860/") {
#tabs>div:first-child {overflow: scroll;}
::-webkit-scrollbar {
/*width: 8px;
height: 8px;*/
width: 5px;
height: 5px;
background-color: transparent;
}
}
```

**Comment by Piscabo** [comment]
I have the same problem, I have a few extensions and can't see half of them as it goes offscreen! Can't get to settings or any other beyond the display limit?

**Comment by neoOpus** [comment]
[**@Piscabo**](https://github.com/Piscabo) commented on [Mar 24, 2023, 2:36 PM EDT](https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/9#issuecomment-1483249792 "2023-03-24T18:36:10Z - Replied by Github Reply Comments"):
> I have the same problem, I have a few extensions and can't see half of them as it goes offscreen! Can't get to settings or any other beyond the display limit?

use my solution

**Comment by Piscabo** [comment]
> that you can add to Stylus or Stylish (or any other userstyle manager extension)

Thanks, but I don't know these files that you refer to, and in what folder? "that you can add to **Stylus or Stylish** (or any other userstyle manager extension)". Can't you just share the file and tell me in which folder it needs to go. Thanks.

**Comment by neoOpus** [comment]
[**@Piscabo**](https://github.com/Piscabo) commented on [Mar 26, 2023, 4:27 PM EDT](https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/9#issuecomment-1484213737 "2023-03-26T20:27:21Z - Replied by Github Reply Comments"):
> > that you can add to Stylus or Stylish (or any other userstyle manager extension)
> 
> Thanks, but I don't know these files that you refer to, and in what folder? "that you can add to **Stylus or Stylish** (or any other userstyle manager extension)". Can't you just share the file and tell me in which folder it needs to go. Thanks.

Stylus browser extension is available for [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne), [Firefox](https://addons.mozilla.org/firefox/addon/styl-us/) and [Opera](https://addons.opera.com/extensions/details/stylus/) browsers.

Install it then, copy the [codeblock](https://github.com/canisminor1990/sd-web-ui-kitchen-theme/issues/9#issuecomment-1476103360) and paste it here :

extension://clngdbkpkpeebahjckkjfobafhncgmne/edit.html

Then save the file and refresh the SD tab, you will be able to scroll horizontally with  `Shift + Mouse Scroll Wheel` OR `mouse middle button Tilt`

**Comment by Piscabo** [comment]
I found a more straightforward fix: This gives a scrollable tab and not a cut-off.  Replace this in the Style.css file Line 904. I just tested it on my own, so make a backup of the original. In my case, I can scroll the tabs, as I'm using a desktop interface. To scroll: Shift +Mouse Wheel

#tabs > div:first-child {
  position: fixed;
  top: 90px;
  z-index: 1000;
  flex-wrap: nowrap;
  width: 100%;
  border: none;
  display: flex;
  flex-wrap: wrap;
  overflow-x: auto;
}

**Comment by dsully** [comment]
@canisminor1990 I just updated to the latest HEAD and this is still broken.
